version: "3.8"

services:
  backend:
    build:
      context:
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context:
      dockerfile: docker/Dockerfile.frontend

  ws:
    build:
      context:
      dockerfile: docker/Dockerfile.ws
